root: ./

structure: 
  readme: README.md
  summary: SUMMARY.md

redirects: 
  other/events : ./tutorials/advanced-development/promise-events/promise-events.md
  other/more-modules : ./tutorials/core-concepts/modules/more-modules.md
  other/nunjucks-filters : ./tutorials/core-concepts/working-with-templates/nunjucks-filters.md
  tutorials/howtos/trim-index : ./tutorials/advanced-development/advanced-pieces-topics/next-previous-links.md
  tutorials/howtos/hide-index-page : ./tutorials/advanced-development/advanced-pieces-topics/next-previous-links.md
  tutorials/howtos/what-to-do-when-you-are-locked-out-of-apostrophe : ./tutorials/core-concepts/users-and-permissions/user-login-and-password.md